# Generated by Django 5.2.3 on 2025-06-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_abstractuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutomer',
            name='status',
            field=models.CharField(blank=True, choices=[('cancel', 'Cancel'), ('pending', 'Pending'), ('fulfilled', 'Fulfilled')], max_length=50, null=True),
        ),
    ]
